# Generated by Django 5.2.8 on 2025-11-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
    ]
