# Generated by Django 5.2.8 on 2025-11-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_max_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_min_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating'), ('text', 'Text'), ('dropdown', 'Dropdown'), ('multiple_choice', 'Multiple Choice'), ('linear_scale', 'Linear Scale'), ('paragraph', 'Paragraph')], max_length=20),
        ),
    ]
