# Generated by Django 5.2 on 2025-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_answer_choice_question_options_question_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='employee_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('survey', 'employee_identifier')},
        ),
    ]
