# Generated by Django 5.2 on 2025-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_response_employee_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_chars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
