# Generated by Django 5.2 on 2025-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_backfill_linear_scale_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating_display_style',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
