# Generated by Django 5.2.8 on 2025-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_survey_header_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating'), ('text', 'Text'), ('regions', 'Regions'), ('dropdown', 'Dropdown'), ('multiple_choice', 'Multiple Choice'), ('linear_scale', 'Linear Scale'), ('paragraph', 'Paragraph')], max_length=20),
        ),
    ]
